apiVersion: v1
data: 
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::202789759365:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-REM7IEQ73751
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::202789759365:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: "[]\n"
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-28T02:38:28Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "834"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: b2a043af-2a30-4266-a164-ab1bf1863d72

