apiVersion: v1
data: 
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::202789759365:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-REM7IEQ73751
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::202789759365:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: "[]\n"
kind: ConfigMap
metadata: 
  creationTimestamp: "2020-06-26T18:55:21Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "790"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: df1c3150-b3c9-40ac-b8a0-ffa2a4af7fec
